### ISSUE TITLE
clockworkspace 、 chisel_guide 文件夹不存在于仓库中，本地仓库需要检查/重新设置远程仓库

### ISSUE THREAD

**Issue by SeraphJACK** [CFPAOrg/I18nUpdateMod#25]
```
Error while updating language file: 
java.nio.file.NoSuchFileException: /home/sj/.I18nUpdateMod/I18nRepo/assets/clockworkphase
```

**Comment by SeraphJACK** [comment]
```
[21:29:16] [I18n-Download-Thread/ERROR] [i18nmod]: Error while fetching repository: 
org.eclipse.jgit.api.errors.InvalidRemoteException: Invalid remote: origin0
	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:252) ~[FetchCommand.class:?]
	at org.cfpa.i18nupdatemod.git.ResourcePackRepository.fetch(ResourcePackRepository.java:84) ~[ResourcePackRepository.class:?]
	at org.cfpa.i18nupdatemod.download.RepoUpdateManager.lambda$start$0(RepoUpdateManager.java:110) ~[RepoUpdateManager.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
```

**Comment by SeraphJACK** [comment]
```bash
$ git remote show origin0
remote: Coding 提示: Repository not found.
remote: Git 仓库找不到。
fatal: 仓库 'https://git.dev.tencent.com/dtid_07bf67d98cf2ab4b/Minecraft-Mod-Language-Package.git/' 未找到
```

仓库炸了？？

**Comment by SeraphJACK** [comment]
而且从 GitHub 的仓库 1.12.2-release 分支 pull 成功之后也没有 clockworkphase 这个文件夹

**Comment by xinyuan-liu** [comment]
之前的腾讯仓库是我测试用的，现在换了

**Comment by xinyuan-liu** [comment]
至于会报错是因为release branch好久没更新了，CI脚本还没写

**Comment by SeraphJACK** [comment]
~~那刚刚那个 Alpha Release 岂不是很尴尬~~

**Comment by xinyuan-liu** [comment]
应该会fallback到github啊

**Comment by SeraphJACK** [comment]
但是已经 Release 了，旧的仓库好像包在里面（

**Comment by xinyuan-liu** [comment]
偷偷换一个（

**Comment by SeraphJACK** [comment]
现在这两个文件夹不存在会导致 mod 一直认为玩家新增了 mod，导致一直显示公告（（

**Comment by xinyuan-liu** [comment]
> 现在这两个文件夹不存在会导致 mod 一直认为玩家新增了 mod，导致一直显示公告（（

那我们就偷偷建个空的23333

**Comment by SeraphJACK** [comment]
我刚想测试加的不存在给玩家反馈的功能你就给我加上了...

**Comment by SeraphJACK** [comment]
~~为什么又要 merge 了~~

**Comment by xinyuan-liu** [comment]
release branch都push了，
remote list检查和重新设置也做了，
不存在的汉化会放一个空文件夹。
