### ISSUE TITLE
关于自然灵气(NaturesAura-r18)模组的指南书BUG

### ISSUE THREAD

**Issue by lomplomp05** [CFPAOrg/I18nUpdateMod#34]
以下是Log
```
[20:15:56] [Client thread/INFO]: [vazkii.patchouli.client.book.BookContents:reload:163]: com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated array at line 32 column 10 path $.pages[5]
[20:15:56] [Client thread/INFO]: [vazkii.patchouli.client.book.BookContents:reload:163]: 	at com.google.gson.Gson.fromJson(Gson.java:902)
[20:15:56] [Client thread/INFO]: [vazkii.patchouli.client.book.BookContents:reload:163]: 	at com.google.gson.Gson.fromJson(Gson.java:825)
[20:15:56] [Client thread/INFO]: [vazkii.patchouli.client.book.BookContents:reload:163]: 	at vazkii.patchouli.client.book.BookContents.loadEntry(BookContents.java:203)
[20:15:56] [Client thread/INFO]: [vazkii.patchouli.client.book.BookContents:reload:163]: 	at vazkii.patchouli.client.book.BookContents.lambda$reload$1(BookContents.java:140)
[20:15:56] [Client thread/INFO]: [vazkii.patchouli.client.book.BookContents:reload:163]: 	at vazkii.patchouli.client.book.BookContents$$Lambda$941/1172885425.accept(Unknown Source)
[20:15:56] [Client thread/INFO]: [vazkii.patchouli.client.book.BookContents:reload:163]: 	at java.util.ArrayList.forEach(ArrayList.java:1249)
[20:15:56] [Client thread/INFO]: [vazkii.patchouli.client.book.BookContents:reload:163]: 	at vazkii.patchouli.client.book.BookContents.reload(BookContents.java:140)
[20:15:56] [Client thread/INFO]: [vazkii.patchouli.client.book.BookContents:reload:163]: 	at vazkii.patchouli.common.book.Book.reloadContents(Book.java:204)
[20:15:56] [Client thread/INFO]: [vazkii.patchouli.client.book.BookContents:reload:163]: 	at vazkii.patchouli.common.book.BookRegistry$$Lambda$938/1954812077.accept(Unknown Source)
[20:15:56] [Client thread/INFO]: [vazkii.patchouli.client.book.BookContents:reload:163]: 	at java.util.HashMap$Values.forEach(HashMap.java:972)
[20:15:56] [Client thread/INFO]: [vazkii.patchouli.client.book.BookContents:reload:163]: 	at vazkii.patchouli.common.book.BookRegistry.reload(BookRegistry.java:87)
[20:15:56] [Client thread/INFO]: [vazkii.patchouli.client.book.BookContents:reload:163]: 	at vazkii.patchouli.client.base.ClientProxy.loadComplete(ClientProxy.java:32)
[20:15:56] [Client thread/INFO]: [vazkii.patchouli.client.book.BookContents:reload:163]: 	at vazkii.patchouli.common.base.Patchouli.loadComplete(Patchouli.java:47)
[20:15:56] [Client thread/INFO]: [vazkii.patchouli.client.book.BookContents:reload:163]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[20:15:56] [Client thread/INFO]: [vazkii.patchouli.client.book.BookContents:reload:163]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[20:15:56] [Client thread/INFO]: [vazkii.patchouli.client.book.BookContents:reload:163]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[20:15:56] [Client thread/INFO]: [vazkii.patchouli.client.book.BookContents:reload:163]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[20:15:56] [Client thread/INFO]: [vazkii.patchouli.client.book.BookContents:reload:163]: 	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
[20:15:56] [Client thread/INFO]: [vazkii.patchouli.client.book.BookContents:reload:163]: 	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
[20:15:56] [Client thread/INFO]: [vazkii.patchouli.client.book.BookContents:reload:163]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[20:15:56] [Client thread/INFO]: [vazkii.patchouli.client.book.BookContents:reload:163]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[20:15:56] [Client thread/INFO]: [vazkii.patchouli.client.book.BookContents:reload:163]: 	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
[20:15:56] [Client thread/INFO]: [vazkii.patchouli.client.book.BookContents:reload:163]: 	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
[20:15:56] [Client thread/INFO]: [vazkii.patchouli.client.book.BookContents:reload:163]: 	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
[20:15:56] [Client thread/INFO]: [vazkii.patchouli.client.book.BookContents:reload:163]: 	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
[20:15:56] [Client thread/INFO]: [vazkii.patchouli.client.book.BookContents:reload:163]: 	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
[20:15:56] [Client thread/INFO]: [vazkii.patchouli.client.book.BookContents:reload:163]: 	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
[20:15:56] [Client thread/INFO]: [vazkii.patchouli.client.book.BookContents:reload:163]: 	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
[20:15:56] [Client thread/INFO]: [vazkii.patchouli.client.book.BookContents:reload:163]: 	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
[20:15:56] [Client thread/INFO]: [vazkii.patchouli.client.book.BookContents:reload:163]: 	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
[20:15:56] [Client thread/INFO]: [vazkii.patchouli.client.book.BookContents:reload:163]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[20:15:56] [Client thread/INFO]: [vazkii.patchouli.client.book.BookContents:reload:163]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[20:15:56] [Client thread/INFO]: [vazkii.patchouli.client.book.BookContents:reload:163]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[20:15:56] [Client thread/INFO]: [vazkii.patchouli.client.book.BookContents:reload:163]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[20:15:56] [Client thread/INFO]: [vazkii.patchouli.client.book.BookContents:reload:163]: 	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
[20:15:56] [Client thread/INFO]: [vazkii.patchouli.client.book.BookContents:reload:163]: 	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
[20:15:56] [Client thread/INFO]: [vazkii.patchouli.client.book.BookContents:reload:163]: 	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
[20:15:56] [Client thread/INFO]: [vazkii.patchouli.client.book.BookContents:reload:163]: 	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
[20:15:56] [Client thread/INFO]: [vazkii.patchouli.client.book.BookContents:reload:163]: 	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
[20:15:56] [Client thread/INFO]: [vazkii.patchouli.client.book.BookContents:reload:163]: 	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
[20:15:56] [Client thread/INFO]: [vazkii.patchouli.client.book.BookContents:reload:163]: 	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
[20:15:56] [Client thread/INFO]: [vazkii.patchouli.client.book.BookContents:reload:163]: 	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
[20:15:56] [Client thread/INFO]: [vazkii.patchouli.client.book.BookContents:reload:163]: 	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:757)
[20:15:56] [Client thread/INFO]: [vazkii.patchouli.client.book.BookContents:reload:163]: 	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
[20:15:56] [Client thread/INFO]: [vazkii.patchouli.client.book.BookContents:reload:163]: 	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:535)
[20:15:56] [Client thread/INFO]: [vazkii.patchouli.client.book.BookContents:reload:163]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
[20:15:56] [Client thread/INFO]: [vazkii.patchouli.client.book.BookContents:reload:163]: 	at net.minecraft.client.main.Main.main(SourceFile:123)
[20:15:56] [Client thread/INFO]: [vazkii.patchouli.client.book.BookContents:reload:163]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[20:15:56] [Client thread/INFO]: [vazkii.patchouli.client.book.BookContents:reload:163]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[20:15:56] [Client thread/INFO]: [vazkii.patchouli.client.book.BookContents:reload:163]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[20:15:56] [Client thread/INFO]: [vazkii.patchouli.client.book.BookContents:reload:163]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[20:15:56] [Client thread/INFO]: [vazkii.patchouli.client.book.BookContents:reload:163]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[20:15:56] [Client thread/INFO]: [vazkii.patchouli.client.book.BookContents:reload:163]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[20:15:56] [Client thread/INFO]: [java.lang.Throwable:printStackTrace:634]: Caused by: com.google.gson.stream.MalformedJsonException: Unterminated array at line 32 column 10 path $.pages[5]
[20:15:56] [Client thread/INFO]: [java.lang.Throwable:printStackTrace:634]: 	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1559)
[20:15:56] [Client thread/INFO]: [java.lang.Throwable:printStackTrace:634]: 	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:476)
[20:15:56] [Client thread/INFO]: [java.lang.Throwable:printStackTrace:634]: 	at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:414)
[20:15:56] [Client thread/INFO]: [java.lang.Throwable:printStackTrace:634]: 	at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:71)
[20:15:56] [Client thread/INFO]: [java.lang.Throwable:printStackTrace:634]: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:129)
[20:15:56] [Client thread/INFO]: [java.lang.Throwable:printStackTrace:634]: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:220)
[20:15:56] [Client thread/INFO]: [java.lang.Throwable:printStackTrace:634]: 	at com.google.gson.Gson.fromJson(Gson.java:887)
[20:15:56] [Client thread/INFO]: [java.lang.Throwable:printStackTrace:634]: 	... 52 more
```

PS: http://issues.cfpa.team/ 我联不上 会不会是因为台湾网路问题?

**Comment by SeraphJACK** [comment]
请在[汉化资源包仓库中提交问题](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/issues/new)，这不是 I18nUpdateMod 的问题。
